### ISSUE TITLE
New delimiter : TAB

### ISSUE THREAD

**Issue by MilleMiles** [blue-yonder/di-csv2xml#16]
It would be useful if di-csv2xml could be compatible with files contains the tab character as delimiter.
The command line could be: -d TAB

**Comment by pacman82** [comment]
Hello @MilleMiles! The tool is already able to work with tabs. You can use the `--delimiter` (or short `-d`) option. In bash the command line looks like this:

```shell
di-csv2xml -i tabs.csv -d ' ' Category
``` 

How you pass the TAB ascii character on the command line depends on the shell you are using. In bash I start with a single quote `'`. I then press `Ctrl + V` in order to suppress the tab extension and then press `TAB`. Then I finish with another single quote `'` in order to surround the `TAB` character.
