### ISSUE TITLE
thread 'main' panicked

### ISSUE THREAD

**Issue by MilleMiles** [blue-yonder/di-csv2xml#6]
Hello,

Nice tool, but I've an error:
thread 'main' panicked at 'byte index 75 is not a char boundary; it is inside 'é' (bytes 74..76) of `4 délégués titulaires et 4 délégués suppléants pour le Conseil général de l'Aisne, 2 délégués titulaires et 2 délégués suppléants pour Guise`', src\libcore\str\mod.rs:2109:5

File:
[banatic.zip](https://github.com/blue-yonder/di-csv2xml/files/2823178/banatic.zip)

Command line:
di-csv2xml banatic -d @ -i banatic.csv -o banatic.xml

How can I fix it?

**Comment by pacman82** [comment]
Hello, sorry for being unresponsive. Somehow I did not take note of the github notification. The problem seems to be within the escape_str function. It seems to somehow screw up the utf8 encoding. In the meantime, I published the `quickxml` branch. It is somewhat slower, but does not exhibit the bug, due to using its own function for escaping xml. It is going to produce the same output, although it might sneak in an additional `\r` at linebreaks on windows systems.

**Comment by pacman82** [comment]
@MilleMiles I released version 1.0.6, which fixes the panic. Thanks again for reporting the Bug and providing a small reproducing example.

Speaking of which: While the tool now will not report an error for the input you provided, the output can not be considered valid XML either, as whitespaces are not allowed within markup names. Please keep in mind that this tool is specifically designed to help customers of Blue Yonder during on-boarding. I think you have a different use case.
